[package]
name = "christmas-2020"
version = "0.1.0"
authors = ["Ernest Wong <sudo@ernestwong.nz>"]
edition = "2018"

[dependencies]
bevy = "0.4"
bevy_rapier2d = { git = "https://github.com/Fedcomp/bevy_rapier", branch = "bevy-0.4" }
bevy_prototype_lyon = { git = "https://github.com/davidB/bevy_prototype_lyon", branch = "bevy_0.4" }
rand = "0.8.0"
# bevy_rapier2d = "0.6.2"
# bevy_prototype_lyon = "0.1.3"
