[package]
name = "christmas-2020"
version = "0.1.0"
authors = ["Ernest Wong <sudo@ernestwong.nz>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[features]
inspect-control-config = []
debug-fly-camera = [
    "bevy_fly_camera",
]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]
native = [
  "bevy/bevy_wgpu",
]
web = [
  "bevy_webgl2"
]
dynamic = [
  "bevy/dynamic",
]
server = []

[dependencies]
bevy = {version = "0.4", default-features = false}
bevy-contrib-inspector = "0.5.1"
bevy_fly_camera = {version = "0.6.0", optional = true}
bevy_prototype_lyon = {git = "https://github.com/Nilirad/bevy_prototype_lyon", branch = "master"}
bevy_webgl2 = {version = "0.4.0", optional = true}
bevy_prototype_frameshader = {path = "crates/bevy_prototype_frameshader"}
bevy_prototype_networked_physics = {path = "crates/bevy_prototype_networked_physics"}
bevy_prototype_transform_tracker = {path = "crates/bevy_prototype_transform_tracker"}
nphysics2d = "0.18"
nalgebra = {version = "0.23.2", features = ["serde-serialize"]}
lyon = "0.16.2"
num = "0.3.1"
serde="1.0.118"
splines = "3.5.1"
winit = "0.24.0"

[patch.crates-io]
bevy_webgl2 = {path = "patches/bevy_webgl2"}
nphysics2d = {path = "patches/nphysics/build/nphysics2d"}
