[package]
name = "christmas-2020"
version = "0.1.0"
authors = ["Ernest Wong <sudo@ernestwong.nz>"]
edition = "2018"

[features]
inspect-control-config = []
debug-fly-camera = []

[dependencies]
bevy_prototype_lyon = { git = "https://github.com/davidB/bevy_prototype_lyon", branch = "bevy_0.4" }
# bevy_prototype_lyon = "0.1.3"
rand = "0.8.0"
nphysics2d = "0.18"
lyon = "0.16.2"
num = "0.3.1"
splines = "3.5.1"
bevy_fly_camera = "0.6.0"
bevy-contrib-inspector = "0.5.1"

[dependencies.bevy]
version = "0.4"
features = ["dynamic"]
